name: Vite Build

on:
  workflow_dispatch: # 수동 실행

  pull_request: # PR이 열릴 때마다 실행
    branches:
      - main

permissions:
  contents: write # 레포지토리 콘텐츠에 대한 쓰기 권한
  actions: read # 액션에 대한 읽기 권한
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      VITE_PUBLIC_URL: ${{ vars.VITE_PUBLIC_URL }}
      VITE_ONE_SIGNAL_APP_ID: ${{ secrets.VITE_ONE_SIGNAL_APP_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm ci # 의존성 설치

      - name: Build Vite project
        env:
          VITE_AUTH_PARCEL_URL: ${{ vars.VITE_GH_PAGE_AUTH_PARCEL_URL }}
        run: |
          npm run build

      - name: Build Vite For single-spa
        env:
          VITE_AUTH_PARCEL_URL: ${{ vars.VITE_AUTH_PARCEL_URL }}
        run: |
          npm run build:single-spa

      - name: Upload Artifact
        uses: actions/upload-artifact@v4 # 아티팩트를 업로드하는 액션
        with:
          name: build-artifact # 아티팩트 이름
          path: dist
